# This is a basic workflow to help you get started with Actions

name: Consulta Token

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 8,13 * * *' # Executar às 8h da manhã e às 18h da noite
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
          
      # Runs a single command using the runners shell      
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      # Comando para instalar biblioteca de email   
      - name: Instalar cliente de e-mail
        run: sudo apt-get update && sudo apt-get install -y mailutils
        
      # Runs a set of commands using the runners shell
      - name: Step 3 Execute collection
        run: newman run ./AutomacaoToken-ci.json -e ./retornoToken-env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
   
      # Runs a set of commands using the runners shell
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > C:\Users\Savio/.ssh/id_rsa
          chmod 600 C:\Users\Savio/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configurar Agente SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add C:\Users\Savio/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Enviar Email
      - name: Enviar e-mail com resultado
        uses: mxschmitt/action-tmate@master
        with:
          session-name: email-session
          command: |
            echo "Assunto: Resultado do GitHub Actions" > email.txt
            echo "O resultado do seu trabalho está anexado." >> email.txt
            mail -s "Resultado do GitHub Actions" savioborges2012@gmail.com < email.txt
